version: '3'
services:
  app:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - postgres
    - redis
  redis:
     image: redis
     container_name: redis
     expose:
       - 6379
  postgres:
    image: postgres:11.1
    ports:
     - "5431:5432"
    environment:
     - POSTGRES_PASSWORD=urspassword
     - POSTGRES_USER=ursuser
     - POSTGRES_DB=urs
